# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 06:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('delta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('gender', models.CharField(max_length=1)),
                ('postcode', models.CharField(max_length=5)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(max_length=255)),
                ('point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_point', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('point_rate', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserLevel'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='wishlist',
            field=models.ManyToManyField(to='product.Product'),
        ),
        migrations.AddField(
            model_name='pointhistory',
            name='userinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo'),
        ),
        migrations.AlterUniqueTogether(
            name='userinfo',
            unique_together=set([('phone',)]),
        ),
    ]
