# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20170415_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='userinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='user.UserInfo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='tid',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
